import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import logo from "@/assets/logo.png";
export default function HeaderApp({ navItems, unreadCount, onClickNotifications, user, onLogin, onLogoClick, }) {
    return (_jsx("header", { className: "h-16 border-b border-[color:var(--color-border-subtle)] bg-[color:var(--color-bg-elev-1)] text-[color:var(--color-fg-primary)]", children: _jsx("div", { className: "mx-auto px-4", style: { maxWidth: "var(--layout-max)" }, children: _jsxs("div", { className: "grid grid-cols-[auto,1fr,auto] items-center gap-4 h-16", children: [_jsx("button", { onClick: onLogoClick, className: "shrink-0 flex items-center", children: _jsx("div", { className: "flex items-center", style: { width: "var(--brand-logo-w)", height: "var(--brand-logo-h)", transform: "translateY(var(--brand-logo-offset-y)" }, children: _jsx("img", { src: logo, alt: "ReadOur", className: "block", style: {
                                    height: "100%",
                                    width: "auto",
                                } }) }) }), _jsx("nav", { className: "flex justify-center", children: _jsx("ul", { className: "flex items-stretch h-full text-sm md:text-base font-medium text-[color:var(--color-fg-muted)]", children: navItems.map((item, idx) => (_jsxs("li", { className: "relative flex items-center px-3 md:px-4", children: [_jsxs("button", { onClick: item.onClick, className: [
                                            "relative h-full flex items-center pb-4",
                                            item.active
                                                ? "text-[color:var(--color-fg-primary)] font-semibold"
                                                : "hover:text-[color:var(--color-fg-primary)]",
                                        ].join(" "), children: [item.label, item.active && (_jsx("span", { className: "absolute -bottom-[1px] left-0 right-0 h-[2px] bg-[color:var(--color-fg-primary)]" }))] }), idx < navItems.length - 1 && (_jsx("span", { className: "absolute right-0 top-1/2 -translate-y-1/2 h-4 w-px bg-[color:var(--color-border-subtle)]" }))] }, item.key))) }) }), _jsxs("div", { className: "shrink-0 flex items-center gap-3 justify-end", children: [_jsxs("button", { onClick: onClickNotifications, className: "relative w-10 h-10 grid place-items-center rounded-[var(--radius-md)] border border-[color:var(--color-border-subtle)] bg-[color:var(--color-bg-elev-1)] hover:bg-[color:var(--color-bg-hover)]", "aria-label": "\uC54C\uB9BC", children: [_jsx("span", { role: "img", "aria-hidden": "true", children: "\uD83D\uDD14" }), unreadCount > 0 && (_jsx("span", { className: "absolute -top-1 -right-1 min-w-5 h-5 px-1 grid place-items-center rounded-full text-[10px] font-bold bg-[color:var(--color-accent)] text-[color:var(--color-on-accent)]", children: unreadCount > 99 ? "99+" : unreadCount }))] }), user ? (_jsx("img", { src: user.avatarUrl || "", alt: user?.name || "user", className: "w-9 h-9 rounded-full object-cover border border-[color:var(--color-border-subtle)]" })) : (_jsx("button", { onClick: onLogin, className: "inline-flex items-center gap-2 h-9 px-3 rounded-full border border-[color:var(--btn-primary-border)] bg-[color:var(--btn-primary-bg)] text-[color:var(--btn-primary-fg)] text-sm font-medium", children: "\uB85C\uADF8\uC778" }))] })] }) }) }));
}
